// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krpzcuhklaezqndpmsur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtycHpjdWhrbGFlenFuZHBtc3VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNDE4MTAsImV4cCI6MjA3MjcxNzgxMH0.YrXOoA3wzihYAkFOKsTqgzlZ21rgPYpLyeTSuYd4vYU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});